### ISSUE TITLE
Compatibility with Elekstube IPS Pro

### ISSUE THREAD

**Issue by RedFox-Fr** [SmittyHalibut/EleksTubeHAX#44]
Hi,

Is your project compatible with the EleksTube IPS Pro ?
https://fr.aliexpress.com/item/1005004836024662.html

Do you know if this product has the problem with the 5V power ?

Best Regards,

**Comment by aly-fly** [comment]
If you send me the Pro version, we will make it compatible (if it isn't already).  I am in EU so shipping is easy.

I don't understand the 5V question.  All these clocks run on USB-C.

**Comment by RedFox-Fr** [comment]
In the Readme.md

> Hardware modification
> Original EleksTube has a few problems in the hardware design. Most notably it forces 5V signals into ESP32 which is not happy about it. And it is outside of safe operating limits. This will extend the lifetime of ESP32. Mine died because of this...

I don't know what is exactly an "Original Elekstube". Just the very first model of Elekstube, or an Elekstube made by EleksMaker…

**Comment by aly-fly** [comment]
There are a few versions out there, originals, copies and modified versions. Personally I have only analyzed one (original).

**Comment by SmittyHalibut** [comment]
@RedFox-Fr None of us have the Pro version, so we don't know anything about it.  If you try it out and it works, let us know!  If you try it out and you have to modify some things to make it work, submit a pull request! (but please retain backward compatibility)  If you try and can't make it work, well, bummer, but that's also good to know.

**Comment by aly-fly** [comment]
>... If you try and can't make it work, well, bummer, but that's also good to know.

If you can't get it working - I assume you are form France, so it would be just a few euros to send the clock to me (Slovenia) for analysis and then I return it to you in working condition.

**Comment by RedFox-Fr** [comment]
I don't own EleksTube for now.
And finally I just ordered a Marvel Tubes… There is a speaker !

http://www.unitedcreation.co/marvel-tubes/?lang=en
https://fr.aliexpress.com/item/1005004925188446.html

Nextube was also in the race, but the screen are too small :(
https://rotrics.com/pages/nextube

**Comment by judge2005** [comment]
This won’t work on Elekstube Pro, they switched to using the ESP32 PICO so some pins have moved, but most importantly the firmware is now protected so not only can you not read the original firmware, but you also can’t upload new firmware.

**Comment by aly-fly** [comment]
> firmware is now protected

I quickly browsed through the [esp32-pico-d4](https://espressif.com/sites/default/files/documentation/esp32-pico-d4_datasheet_en.pdf) datasheet and found no reference on any FW protection.  Also the [dev board ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-pico-kit.html#get-started-pico-kit-v4-board-front) has same UART interface as any other ESP32. @judge2005 can you please share more light on this protections that I can't find?

**Comment by judge2005** [comment]
> > firmware is now protected
> 
> 
> 
> I quickly browsed through the [esp32-pico-d4](https://espressif.com/sites/default/files/documentation/esp32-pico-d4_datasheet_en.pdf) datasheet and found no reference on any FW protection.  Also the [dev board ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-pico-kit.html#get-started-pico-kit-v4-board-front) has same UART interface as any other ESP32. @judge2005 can you please share more light on this protections that I can't find?

It's not specific to the pico, it's a feature of all ESP32 chips. I was making two separate points.

The first is that their switch to the pico meant they had to change some on assignments - the pico uses some pins internally and they happen to have used those pins in their previous version.

The second point is that with this version they have used the [ESP32 protection features](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html). The contents of the chip can no longer be read or overwritten.

I have verified this with their v2 hardware. You can see the different pin assignments in the GLOBAL_DEFINES.h of my EleksTubeIPS repo.

**Comment by aly-fly** [comment]
Thanks, I read through the documentation on the link. It makes more sense now. A bit similar to Level 1 and Level 2 flash protection on STM32 devices. 
If they left the device in "development" mode, then encryption can be disabled and chip used unencrypted from then on, with custom firmware. If switched to "release" mode, maybe also disabled UART bootloader, then part is more or less fully locked. 
If you have the Pro version you can check if it can be [unlocked](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html#disabling-flash-encryption)?

**Comment by judge2005** [comment]
> Thanks, I read through the documentation on the link. It makes more sense now. A bit similar to Level 1 and Level 2 flash protection on STM32 devices. If they left the device in "development" mode, then encryption can be disabled and chip used unencrypted from then on, with custom firmware. If switched to "release" mode, maybe also disabled UART bootloader, then part is more or less fully locked. If you have the Pro version you can check if it can be [unlocked](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html#disabling-flash-encryption)?

I will try to take a look this evening, however I am not hopeful. [This page](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v2.html) talks about secure booting, and in particular it says this:

> Please note that enabling Secure Boot or flash encryption disables the USB-OTG USB stack in the ROM, disallowing updates via the serial emulation or Device Firmware Update (DFU) on that port.

When I try to upload an image using esptool, I just get no response from the device. Same when trying to read the image using esptool. There is some explanatory text [here](https://esp32.com/viewtopic.php?t=29397).

I notice you have another ticket https://github.com/SmittyHalibut/EleksTubeHAX/issues/55 that implies that GEN2 hardware can be flashed, which would be nice. I have the Pro hardware, which is apparently identified by the buttons being on the front - this according to the PC client that EleksMaker provide to update it - when you update it you have to select either the pro firmware or the regular gen2 firmware. I had wondered why there was a difference. Perhaps it is simply that one is protected and the other isn't?

**Comment by aly-fly** [comment]
USB-OTG or DFU require native USB support from the processor itself. This are different things than what is usually used on these simple devices. If you have an USB-to-Serial converter chip on board, this is a classic approach.  And serial bootloader should be working there, unless explicitly disabled. No idea what is the difference between Pro and Gen2. Probably different hardware or functions and you must load correct firmware on it.

**Comment by judge2005** [comment]
> USB-OTG or DFU require native USB support from the processor itself. This are different things than what is usually used on these simple devices. If you have an USB-to-Serial converter chip on board, this is a classic approach. And serial bootloader should be working there, unless explicitly disabled. No idea what is the difference between Pro and Gen2. Probably different hardware or functions and you must load correct firmware on it.

well the documentation is a little confusing. Here is another snipper: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-secure-uart-rom-dl-mode

**Comment by MrMSch** [comment]
Would a firmware dump help here or is everything moot by security?

**Comment by aly-fly** [comment]
Generally it is easier to reverse engineer the hardware than firmware. I personally wouldn't benefit from the firmware dump. 
Maybe some interesting new clock faces could be extracted, if uploaded to the clock and not available otherwise.

**Comment by Martinius79** [comment]
I know, the topic is old, but I am also a bit stuck, like @judge2005. So I want to know, if Gen2 is working or not.
I have two orginal Elekstube Gen2 version clocks here (PR1 and PR2) and can't put them in the download mode...As far as I can see on the boards, the usual two transistor pull down/up for automatic download and reset is present, and the EN pin seems to be connected to the most right button.

But even if the esptool can reset the clock, it always tells me, that it is not in the download mode...so no flash_id or flash read...

Powering on with the button pressed, "does" something, because the normal boot loader routine is not executed...But also no connection with esptool.

I see, that @gamba69 seems to use a PR2 clock, because it is mentioned in the Home Assistant commit of him :)

So my questions are:
How to put the Elekstube PR1 or PR2 hardware into the donwload mode to read and write the flash?
Did anyone read the original firmware from the clock successful? If yes, how?
How is it possible to flash the EleksTubeHAX firmware bin file to the clock?
Did someone disassemble the "original" Elekstube executables to see, how they can flash new firmware via the serial port?

Martinius

**Comment by Martinius79** [comment]
OK, after doing some "research," I now know that my "main" computer has a problem (I guess timing) with the CH34x drivers and the original Elekstube clocks.

I was able to read out the original firmware from both clocks using the "default" ESP32 command on my Dell laptop instead of my tower PC.

Command: `esptool.exe --chip esp32 --port COM6 --baud 115200 --before default_reset --after hard_reset read_flash 0x00000000 0x400000 ./backup1.bin`

The "auto" mode works fine with the laptop but not on my main PC. So if someone has trouble connecting to the newer Elekstube clocks, try another computer...

The clock itself seems to have no "ESP32 protection" active. Reading and writing are no problem.

I also did some research on the original software from Elekstube and found out how they communicate with the clocks over the serial port to "control" the clock, but I didn’t pursue this approach further.

Martinius
