### ISSUE TITLE
Can someone owning an open H401 clone check something?

### ISSUE THREAD

**Issue by MacGyver4B** [SmittyHalibut/EleksTubeHAX#90]
Would this 🕹️ buttons be able to replace the button and still fit in the case?
https://cdn-shop.adafruit.com/datasheets/SKQUCAA010-ALPS.pdf

**Comment by Martinius79** [comment]
Hello MacGyver4B!

I don't think that this "joystick button" will fit easily with the H401 or H402. The problem is the casing, and the fact that the soldered button is not directly accessible from the outside. Instead, there is a long plastic stick and a round plastic piece around it.

I can just post some of the pictures I took to make it clearer.

![PXL_20241011_222424041a](https://github.com/user-attachments/assets/068137d9-d354-4d94-bb27-6fe3a5eafe85)
![PXL_20240527_054206617a](https://github.com/user-attachments/assets/cd5252bb-62b2-4b62-bc9f-7d205fb6dc07)
![PXL_20240526_211359192a](https://github.com/user-attachments/assets/7e1c9281-4a2e-44d1-8c4e-6d72c65c588a)
![PXL_20240526_211114753a](https://github.com/user-attachments/assets/fba9bdd3-d5cc-4194-ab88-b8e3f250bc21)
![PXL_20240526_210739880a](https://github.com/user-attachments/assets/583afdd4-0af1-440d-8fe0-fa7585ea39db)
![PXL_20240526_210803128a](https://github.com/user-attachments/assets/8f2bd071-cedc-4357-aea1-ab31c2a7a320)
![PXL_20240825_110821551a](https://github.com/user-attachments/assets/996b7616-bb41-426f-a29c-fa824939050c)
![PXL_20240825_142809723a](https://github.com/user-attachments/assets/b363bd41-348e-44e0-b7f9-825ca695b075)
![PXL_20240825_142818154a](https://github.com/user-attachments/assets/25cfb704-e875-442b-a126-686e4ff52a6d)
![PXL_20240825_142854782a](https://github.com/user-attachments/assets/42f677c6-0023-4290-ab75-52b7bda59f97)
![PXL_20240825_142955957a](https://github.com/user-attachments/assets/002341c5-dbd8-4a14-a88c-c61a6b0d9d95)
![PXL_20240825_143013515a](https://github.com/user-attachments/assets/6933769f-9a0e-4072-b0c4-0e19336b66ce)

Bye
Martinius

**Comment by MacGyver4B** [comment]
Thank you very much.
I think the original button is 6x6 mm right?
The joystick is 10x10 mm so it would be needed to remove a bit of the PCB to make room for the joystick.
I would say still possible but really no fun to do so.
Was just an idea.
Best regards 
Stefan
